[phases.setup]
nixPkgs = ["gcc", "musl", "musl.dev"]
aptPkgs = ["curl", "build-essential"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",
  "source $HOME/.cargo/env",
  "rustup default stable",
  "rustup target add x86_64-unknown-linux-gnu"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "source $HOME/.cargo/env",
  "cargo build --release",
  "mkdir -p bin",
  "cp target/release/hello-world-api bin/"
]

[start]
cmd = "./bin/hello-world-api" 